-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.machines (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  serial_number character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  created_at timestamp without time zone,
  updated_at timestamp with time zone DEFAULT now(),
  image_url text,
  model character varying,
  manufacturer character varying,
  specifications jsonb DEFAULT '{}'::jsonb,
  notes text,
  department character varying NOT NULL,
  location character varying,
  status character varying NOT NULL DEFAULT 'operational'::character varying,
  health_score integer DEFAULT 100,
  task_assigned boolean DEFAULT false,
  assigned_user character varying,
  asset_category character varying,
  purchase_date date,
  purchase_price numeric DEFAULT 0,
  vendor character varying,
  warranty_expiration date,
  last_maintenance date,
  next_maintenance date,
  maintenance_parts ARRAY,
  telemetry_data jsonb DEFAULT '{}'::jsonb,
  documents jsonb DEFAULT '[]'::jsonb,
  maintenance_schedule jsonb DEFAULT '[]'::jsonb,
  repair_log jsonb DEFAULT '[]'::jsonb,
  purchase_history jsonb DEFAULT '[]'::jsonb,
  fixed_assets jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT machines_pkey PRIMARY KEY (id)
);
CREATE TABLE public.maintenance (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  machine_id bigint,
  task_title text NOT NULL,
  priority text,
  due_date timestamp without time zone,
  status text DEFAULT 'scheduled'::text,
  assigned_to text,
  description text,
  frequency text,
  is_temperature_sensitive boolean DEFAULT false,
  enable_reminder boolean DEFAULT false,
  require_attachment boolean DEFAULT false,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  checklist ARRAY DEFAULT '{}'::jsonb[],
  documents ARRAY DEFAULT '{}'::jsonb[],
  task_logs ARRAY DEFAULT '{}'::jsonb[],
  estimated_cost numeric DEFAULT 0,
  given_by text,
  serial_number text,
  start_date date,
  end_date date,
  CONSTRAINT maintenance_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(id)
);
CREATE TABLE public.maintenance_tasks (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  maintenance_id bigint NOT NULL,
  task_no text NOT NULL,
  description text NOT NULL,
  status text DEFAULT 'pending'::text,
  remarks text,
  sound_of_machine text,
  temperature text,
  maintenance_cost numeric DEFAULT 0,
  image_url text,
  department text,
  is_submitted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  serial_number text,
  task_date date,
  CONSTRAINT maintenance_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_tasks_maintenance_id_fkey FOREIGN KEY (maintenance_id) REFERENCES public.maintenance(id)
);
CREATE TABLE public.repairs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  machine_id bigint,
  machine_serial_no text,
  doer_name text,
  department text,
  machine_part_name text,
  problem_description text,
  priority text,
  expected_delivery_days integer,
  location text,
  image_url text,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  given_by text,
  CONSTRAINT repairs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  employee_name text NOT NULL,
  department text NOT NULL,
  phone_number text,
  employee_code text,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  page_access text DEFAULT 'User'::text CHECK (page_access = ANY (ARRAY['Admin'::text, 'User'::text, 'Viewer'::text])),
  is_active boolean NOT NULL DEFAULT true,
  allowed_pages ARRAY DEFAULT '{}'::text[],
  profile_picture text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);